/*
 * generated by Xtext 2.19.0
 */
package org.palladiosimulator.supporting.prolog.ide;


/**
 * Use this class to register ide components.
 */
public class PrologIdeModule extends AbstractPrologIdeModule {
}
