/*
 * generated by Xtext 2.19.0
 */
package org.palladiosimulator.supporting.prolog;

import org.eclipse.xtext.formatting2.IFormatter2;
import org.palladiosimulator.supporting.prolog.formatting.PrologFormatter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("restriction")
public class PrologRuntimeModule extends AbstractPrologRuntimeModule {
	
	public Class<? extends IFormatter2> bindIFormatter2() {
		return PrologFormatter.class;
	}
	
}
