/*
 * generated by Xtext 2.19.0
 */
package org.palladiosimulator.supporting.prolog;

import org.palladiosimulator.supporting.prolog.model.prolog.PrologPackage;
import org.palladiosimulator.supporting.prolog.model.prolog.directives.DirectivesPackage;
import org.palladiosimulator.supporting.prolog.model.prolog.expressions.ExpressionsPackage;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PrologStandaloneSetup extends PrologStandaloneSetupGenerated {

	public static void doSetup() {
		new PrologStandaloneSetup().createInjectorAndDoEMFRegistration();
	}

	@Override
	public void register(Injector injector) {
		PrologPackage.eINSTANCE.eClass();
		ExpressionsPackage.eINSTANCE.eClass();
		DirectivesPackage.eINSTANCE.eClass();
		super.register(injector);
	}
	
}
