/*
 * generated by Xtext 2.19.0
 */
package org.palladiosimulator.supporting.prolog.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PrologUiModule extends AbstractPrologUiModule {

	public PrologUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
